spring:
  application:
    name: train-ticket
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 1000
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/train
    username: ${DB_USERNAME:core}
    password: ${DB_PASSWORD:rabbit}
    driverClassName: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: seat-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 3
        enable:
          idempotence: true


server:
  port: 8086

